### ISSUE TITLE
Synchronisation notes half -> halt

### ISSUE THREAD

**Issue by persuc** [cjmlgrto/fit3143-notes#1]
Please change "A simple solution is to half the clock for the duration (but this simplistic solution can cause problems)" to "A simple solution is to halt the clock for the duration (but this simplistic solution can cause problems)" under the "Berkeley Algorithm" section of the Synchronisation notes.

**Comment by gh4n** [comment]
Created PR

**Comment by cjmlgrto** [comment]
Good stuff. Cheers folks!
